// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v4.25.1
// source: densecore.proto

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DenseCoreService_ChatCompletion_FullMethodName       = "/densecore.DenseCoreService/ChatCompletion"
	DenseCoreService_StreamChatCompletion_FullMethodName = "/densecore.DenseCoreService/StreamChatCompletion"
	DenseCoreService_ListModels_FullMethodName           = "/densecore.DenseCoreService/ListModels"
	DenseCoreService_LoadModel_FullMethodName            = "/densecore.DenseCoreService/LoadModel"
	DenseCoreService_UnloadModel_FullMethodName          = "/densecore.DenseCoreService/UnloadModel"
	DenseCoreService_GetEmbeddings_FullMethodName        = "/densecore.DenseCoreService/GetEmbeddings"
)

// DenseCoreServiceClient is the client API for DenseCoreService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// DenseCoreService provides LLM inference capabilities
type DenseCoreServiceClient interface {
	// ChatCompletion performs synchronous chat completion
	ChatCompletion(ctx context.Context, in *ChatCompletionRequest, opts ...grpc.CallOption) (*ChatCompletionResponse, error)
	// StreamChatCompletion performs streaming chat completion
	StreamChatCompletion(ctx context.Context, in *ChatCompletionRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ChatCompletionChunk], error)
	// ListModels returns the list of available models
	ListModels(ctx context.Context, in *ListModelsRequest, opts ...grpc.CallOption) (*ListModelsResponse, error)
	// LoadModel loads a model at runtime
	LoadModel(ctx context.Context, in *LoadModelRequest, opts ...grpc.CallOption) (*LoadModelResponse, error)
	// UnloadModel unloads a model
	UnloadModel(ctx context.Context, in *UnloadModelRequest, opts ...grpc.CallOption) (*UnloadModelResponse, error)
	// GetEmbeddings generates embeddings for input text
	GetEmbeddings(ctx context.Context, in *EmbeddingRequest, opts ...grpc.CallOption) (*EmbeddingResponse, error)
}

type denseCoreServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDenseCoreServiceClient(cc grpc.ClientConnInterface) DenseCoreServiceClient {
	return &denseCoreServiceClient{cc}
}

func (c *denseCoreServiceClient) ChatCompletion(ctx context.Context, in *ChatCompletionRequest, opts ...grpc.CallOption) (*ChatCompletionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChatCompletionResponse)
	err := c.cc.Invoke(ctx, DenseCoreService_ChatCompletion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *denseCoreServiceClient) StreamChatCompletion(ctx context.Context, in *ChatCompletionRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ChatCompletionChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DenseCoreService_ServiceDesc.Streams[0], DenseCoreService_StreamChatCompletion_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ChatCompletionRequest, ChatCompletionChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DenseCoreService_StreamChatCompletionClient = grpc.ServerStreamingClient[ChatCompletionChunk]

func (c *denseCoreServiceClient) ListModels(ctx context.Context, in *ListModelsRequest, opts ...grpc.CallOption) (*ListModelsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListModelsResponse)
	err := c.cc.Invoke(ctx, DenseCoreService_ListModels_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *denseCoreServiceClient) LoadModel(ctx context.Context, in *LoadModelRequest, opts ...grpc.CallOption) (*LoadModelResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoadModelResponse)
	err := c.cc.Invoke(ctx, DenseCoreService_LoadModel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *denseCoreServiceClient) UnloadModel(ctx context.Context, in *UnloadModelRequest, opts ...grpc.CallOption) (*UnloadModelResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnloadModelResponse)
	err := c.cc.Invoke(ctx, DenseCoreService_UnloadModel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *denseCoreServiceClient) GetEmbeddings(ctx context.Context, in *EmbeddingRequest, opts ...grpc.CallOption) (*EmbeddingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmbeddingResponse)
	err := c.cc.Invoke(ctx, DenseCoreService_GetEmbeddings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DenseCoreServiceServer is the server API for DenseCoreService service.
// All implementations must embed UnimplementedDenseCoreServiceServer
// for forward compatibility.
//
// DenseCoreService provides LLM inference capabilities
type DenseCoreServiceServer interface {
	// ChatCompletion performs synchronous chat completion
	ChatCompletion(context.Context, *ChatCompletionRequest) (*ChatCompletionResponse, error)
	// StreamChatCompletion performs streaming chat completion
	StreamChatCompletion(*ChatCompletionRequest, grpc.ServerStreamingServer[ChatCompletionChunk]) error
	// ListModels returns the list of available models
	ListModels(context.Context, *ListModelsRequest) (*ListModelsResponse, error)
	// LoadModel loads a model at runtime
	LoadModel(context.Context, *LoadModelRequest) (*LoadModelResponse, error)
	// UnloadModel unloads a model
	UnloadModel(context.Context, *UnloadModelRequest) (*UnloadModelResponse, error)
	// GetEmbeddings generates embeddings for input text
	GetEmbeddings(context.Context, *EmbeddingRequest) (*EmbeddingResponse, error)
	mustEmbedUnimplementedDenseCoreServiceServer()
}

// UnimplementedDenseCoreServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDenseCoreServiceServer struct{}

func (UnimplementedDenseCoreServiceServer) ChatCompletion(context.Context, *ChatCompletionRequest) (*ChatCompletionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ChatCompletion not implemented")
}
func (UnimplementedDenseCoreServiceServer) StreamChatCompletion(*ChatCompletionRequest, grpc.ServerStreamingServer[ChatCompletionChunk]) error {
	return status.Errorf(codes.Unimplemented, "method StreamChatCompletion not implemented")
}
func (UnimplementedDenseCoreServiceServer) ListModels(context.Context, *ListModelsRequest) (*ListModelsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListModels not implemented")
}
func (UnimplementedDenseCoreServiceServer) LoadModel(context.Context, *LoadModelRequest) (*LoadModelResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LoadModel not implemented")
}
func (UnimplementedDenseCoreServiceServer) UnloadModel(context.Context, *UnloadModelRequest) (*UnloadModelResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnloadModel not implemented")
}
func (UnimplementedDenseCoreServiceServer) GetEmbeddings(context.Context, *EmbeddingRequest) (*EmbeddingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetEmbeddings not implemented")
}
func (UnimplementedDenseCoreServiceServer) mustEmbedUnimplementedDenseCoreServiceServer() {}
func (UnimplementedDenseCoreServiceServer) testEmbeddedByValue()                          {}

// UnsafeDenseCoreServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DenseCoreServiceServer will
// result in compilation errors.
type UnsafeDenseCoreServiceServer interface {
	mustEmbedUnimplementedDenseCoreServiceServer()
}

func RegisterDenseCoreServiceServer(s grpc.ServiceRegistrar, srv DenseCoreServiceServer) {
	// If the following call pancis, it indicates UnimplementedDenseCoreServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DenseCoreService_ServiceDesc, srv)
}

func _DenseCoreService_ChatCompletion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChatCompletionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DenseCoreServiceServer).ChatCompletion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DenseCoreService_ChatCompletion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DenseCoreServiceServer).ChatCompletion(ctx, req.(*ChatCompletionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DenseCoreService_StreamChatCompletion_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ChatCompletionRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DenseCoreServiceServer).StreamChatCompletion(m, &grpc.GenericServerStream[ChatCompletionRequest, ChatCompletionChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DenseCoreService_StreamChatCompletionServer = grpc.ServerStreamingServer[ChatCompletionChunk]

func _DenseCoreService_ListModels_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListModelsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DenseCoreServiceServer).ListModels(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DenseCoreService_ListModels_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DenseCoreServiceServer).ListModels(ctx, req.(*ListModelsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DenseCoreService_LoadModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoadModelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DenseCoreServiceServer).LoadModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DenseCoreService_LoadModel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DenseCoreServiceServer).LoadModel(ctx, req.(*LoadModelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DenseCoreService_UnloadModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnloadModelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DenseCoreServiceServer).UnloadModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DenseCoreService_UnloadModel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DenseCoreServiceServer).UnloadModel(ctx, req.(*UnloadModelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DenseCoreService_GetEmbeddings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmbeddingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DenseCoreServiceServer).GetEmbeddings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DenseCoreService_GetEmbeddings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DenseCoreServiceServer).GetEmbeddings(ctx, req.(*EmbeddingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DenseCoreService_ServiceDesc is the grpc.ServiceDesc for DenseCoreService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DenseCoreService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "densecore.DenseCoreService",
	HandlerType: (*DenseCoreServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ChatCompletion",
			Handler:    _DenseCoreService_ChatCompletion_Handler,
		},
		{
			MethodName: "ListModels",
			Handler:    _DenseCoreService_ListModels_Handler,
		},
		{
			MethodName: "LoadModel",
			Handler:    _DenseCoreService_LoadModel_Handler,
		},
		{
			MethodName: "UnloadModel",
			Handler:    _DenseCoreService_UnloadModel_Handler,
		},
		{
			MethodName: "GetEmbeddings",
			Handler:    _DenseCoreService_GetEmbeddings_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamChatCompletion",
			Handler:       _DenseCoreService_StreamChatCompletion_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "densecore.proto",
}
