#ifndef DENSECORE_ENTERPRISE_ABI_H
#define DENSECORE_ENTERPRISE_ABI_H

#include <stdint.h>

#define DENSECORE_ENT_ABI_VERSION_MAJOR 2U
#define DENSECORE_ENT_ABI_VERSION_MINOR 0U
#define DENSECORE_ENT_ABI_VERSION ((DENSECORE_ENT_ABI_VERSION_MAJOR << 16U) | DENSECORE_ENT_ABI_VERSION_MINOR)
#define DENSECORE_ENT_ABI_MAJOR(version) (((version) >> 16U) & 0xFFFFU)

#endif  // DENSECORE_ENTERPRISE_ABI_H
